blank_issues_enabled: true
contact_links:
  - name: Yukki Support
    url: https://t.me/NexusXSupport
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://t.me/Anime_com_Chat
    about: Documentation for getting started with bot.
